import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar';
import Footer from './components/footer';
import StateWrapper from './components/statewrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Anillo de Compromiso',
	description: 'Generated by create next app',
};

const links = [
	{
		label: 'Home',
		route: '/',
	},
	{
		label: 'products',
		route: '/products',
	},
];

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body className={inter.className} suppressHydrationWarning={true}>
				<StateWrapper>
					<Navbar />
					{children}

					<Footer />
				</StateWrapper>
			</body>
		</html>
	);
}
