import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Navbar from './components/navbar';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const links = [
	{
		label: 'Home',
		route: '/',
	},
	{
		label: 'products',
		route: '/products',
	},
	{
		label: 'preguntas-frecuentes',
		route: '/faq',
	}
];

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<head>
				<title>Anillo de Compromiso</title>
			</head>
			<body className={inter.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
